version: '3.8'

services:
  server:
    build: ./server
    container_name: shareit-server
    network_mode: host
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit

  gateway:
    build: ./gateway
    container_name: shareit-gateway
    network_mode: host
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://localhost:9090

  postgres:
    image: postgres:16.1
    container_name: postgres
    network_mode: host
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shareit -d shareit" ]
      interval: 5s
      timeout: 5s
      retries: 5